---
apiVersion: v1
kind: Service
metadata:
  name: rootme-service 
spec:
  selector:
    app: rootme 
  ports:
  - protocol: "TCP"
    nodePort: 30681
    port: 8084
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rootme 
spec:
  selector:
    matchLabels:
      app: rootme 
  replicas: 4
  template:
    metadata:
      labels:
        app: rootme 
    spec:
      containers:
      - name: rootme
        image: localhost:5000/rootme:{{ .Values.imageVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/storage_clients
          name: rootme-volume-storage-clients
      volumes:
      - name: rootme-volume-storage-clients 
        hostPath:
          # directory location on host
          path: /opt/storage_clients
          # this field is optional
          #  type: Directory
          type: DirectoryOrCreate
