name: auto-merge

on:
  pull_request_target:
    branches:
      - master

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.TOKEN }}
          command: "squash and merge"
          approve: false
          target: minor
