name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
      - "requirements.txt"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      run: echo "IMAGE_VERSION=${{ secrets.DOCKERHUB_USERNAME }}/rootme-badge-generator:$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.IMAGE_VERSION }}
    - name: Set artifact
      run: echo ${{ env.IMAGE_VERSION }} > version.txt
    - uses: actions/upload-artifact@v2
      with:
        name: image-version
        path: version.txt
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: image-version
      - name: Compute image version
        run: >
          echo "IMAGE_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Deploy rootme docker container
        run: >-
          (docker rm -f rootme || true) && docker run -d --restart always
          -p 0.0.0.0:38084:80 --name badge_generator
          -v /volume1/docker/rootme/storage_clients:/app/storage_clients
          $IMAGE_VERSION
